[package]
name = "rust_final"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.27"
tokio = { version = "1", features = ["full"] }
iced = { version = "0.6", features = ["tokio"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
serde_json = "1.0"
